Repository nodevault/node-vault, pull requests merged in 2023-05, with the labels that each got.

#218 Tests CI via GH actions
  .github/workflows/lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/write-features.yaml
  .travis.yml
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, greenkeeper

#225 Versions upgrade
  .eslintrc
  .eslintrc.js
  .github/workflows/run-tests.yaml
  .gitignore
  Dockerfile
  example/audits.js
  example/auth.js
  example/auth_approle.js
  example/auth_github.js
  example/auth_kubernetes.js
  example/auth_ldap.js
  example/auth_okta.js
  example/auth_userpass.js
  example/health.js
  example/help.js
  example/init.js
  example/leases.js
  example/mount_postgresql.js
  example/pass_request_options.js
  example/policies.js
  example/secret_mounts.js
  example/status.js
  example/token.js
  example/transit.js
  example/write_read_delete.js
  features.md
  package-lock.json
  package.json
  scripts/write-features.js
  src/commands.js
  src/index.js
  test/integration.js
  test/unit.js
Labels: greenkeeper

#156 Changed write method from PUT to POST
  src/index.js
  test/unit.js
Labels: awaiting changes

#207 Added support for TLS Certificate based Authentication
  features.md
  index.d.ts
  src/commands.js
Labels: enhancement, awaiting changes

#227 Matrix testing for various node versions compatability
  .devcontainer/devcontainer.json
  .github/workflows/lint-and-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/run-tests.yaml
  .github/workflows/security.yaml
  Dockerfile
  docker-compose.yml
  package.json
Labels: enhancement
